(ns yo.slack.team
  (:require [yo.slack.core :as slack]))

(defn access-logs
  "This method is used to get the access logs for users on a team.

  Required arguments are:
  * token -- Authentication token

  Options keywords are:
  * :before -- End of time range of logs to include in results (inclusive)
  * :count -- Number of items to return per page
  * :page -- Page number of results to return."
  ([token]
   (access-logs token {}))
  ([token opts]
   (slack/request-get "team.accessLogs" (conj opts {:token token}))))

(defn billable-info
  "This method lists billable information for each user on the team.

  Required arguments are:
  * token -- Authentication token

  Options keywords are:
  * :user -- A user to retrieve the billable information for."
  ([token]
   (billable-info token {}))
  ([token opts]
   (slack/request-get "team.billableInfo" (conj opts {:token token}))))

(defn info
  "This method provides information about your team.

  Required arguments are:
  * token -- Authentication token."
  [token]
  (slack/request-get "team.info" {:token token}))

(defn integration-logs
  "This method lists the integration activity logs for a team, including when integrations are added, modified and removed. This method can only be called by Admins.

  Required arguments are:
  * token -- Authentication token

  Options keywords are:
  * :app_id -- Filter logs to this Slack app
  * :change_type -- Filter logs with this change type
  * :count -- Number of items to return per page
  * :page -- Page number of results to return
  * :service_id -- Filter logs to this service
  * :user -- Filter logs generated by this user's actions."
  ([token]
   (integration-logs token {}))
  ([token opts]
   (slack/request-get "team.integrationLogs" (conj opts {:token token}))))
