(ns yo.slack.team)

(defn accessLogs
  "This method is used to get the access logs for users on a team.

  Required arguments are:
  * token -- Authentication token

  Options keywords are:
  * :before -- End of time range of logs to include in results (inclusive)
  * :count -- Number of items to return per page
  * :page -- Page number of results to return."
  ([token]
   (accessLogs token {}))
  ([token opts]
   :TODO))

(defn billableInfo
  "This method lists billable information for each user on the team.

  Required arguments are:
  * token -- Authentication token

  Options keywords are:
  * :user -- A user to retrieve the billable information for."
  ([token]
   (billableInfo token {}))
  ([token opts]
   :TODO))

(defn info
  "This method provides information about your team.

  Required arguments are:
  * token -- Authentication token."
  [token]
  :TODO)

(defn integrationLogs
  "This method lists the integration activity logs for a team, including when integrations are added, modified and removed. This method can only be called by Admins.

  Required arguments are:
  * token -- Authentication token

  Options keywords are:
  * :app_id -- Filter logs to this Slack app
  * :change_type -- Filter logs with this change type
  * :count -- Number of items to return per page
  * :page -- Page number of results to return
  * :service_id -- Filter logs to this service
  * :user -- Filter logs generated by this user's actions."
  ([token]
   (integrationLogs token {}))
  ([token opts]
   :TODO))





